# -*- coding: utf-8 -*-
"""Code Snippets

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15K4QfePuLd5PkeGOhoEk_DLj-yWb4RP5

# Code Snippets

## PyTorch
"""

import torch

#텐서 x 생성하기
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(f"텐서 x:\n{x}")

#텐서 크기 확인
print(f"x의 크기: {x.shape}")

#GPU 사용 가능한 경우, GPU로 이동
if torch.cuda.is_available():
  x = x.cuda()
  print("x를 GPU로 이동했습니다.")

"""## OpenCV"""

import cv2
import numpy as np # OpenCV는 내부적으로 NumPy 배열을 사용함

#더미 이미지 생성 (실제 이미지 파일이 없다고 가정한 경우)
dummy_img = np.zeros((100, 150, 3), dtype=np.uint8) #100x150x3 (HxWxC)의 검은색 이미지
#np.unit8: 픽셀 값 범위가 0-255, np.zeros: R,G,B 모두 0으로

#실제 이미지 파일 경로를 사용한다면: img =cv2.imread('image.jpg')
img = dummy_img

#이미지 크기 확인
h, w, c = img.shape
print(f"원본 이미지 크기: {w}x{h} ({c}채널)")

#이미지 크기 조정
resized_img = cv2.resize(img, (50,50))
rh, rw, rc = resized_img.shape
print(f"조정된 이미지 크기: {rw}x{rh}")

"""## NumPy"""

import numpy as np

# 2x3 배열 생성
A = np.array([[1, 2, 3], [4, 5, 6]])
print(f"행렬 A:\n{A}")

# 3x2 배열 생성
B = np.array([[7, 8], [9, 10], [11, 12]])
print(f"\n행렬 B:\n{B}")

# 행렬 곱셈 (A * B) -> 결과는 2x2
C = A@B   # C = np.dot(A, B)도 가능
print(f"\nA와 B의 행렬 곱 (C) : \n{C}")